### PR TITLE
Preserve 'deploy' export for Substrate binaries

### LINKED ISSUE #108: wasm-build renames substrate 'deploy' export
https://github.com/paritytech/wasm-utils/blob/24b97b517abd8419ddf1551fddac671c616797ed/src/pack.rs#L203-L205

This causes it to fail a deploy time check in Substrate:
https://github.com/paritytech/substrate/blob/4f993e6ac8f55cfe8d035ecb95fa5e4d1cf34b8b/srml/contract/src/wasm/prepare.rs#L181-L183

I'm not sure on the intended behaviour here so this issue may need to be moved to the substrate repo. accordingly

### PR DESCRIPTION
**Pull request by holygits**
Closes #108 

Don't rename create symbol for substrate ctor binaries
Refactor TargetRuntime as enum

### CODE REVIEW

File: src/pack.rs [hunk 1]
```diff
@@ -195,13 +195,17 @@ pub fn pack_instance(raw_module: Vec<u8>, mut ctor_module: elements::Module, tar
             ])).build()
             .build()
         .build();
+    
+    if let TargetRuntime::Substrate(_) = target {
+        return Ok(new_module)
+    }
```
Comment (pepyakin) [inline src/pack.rs]: I'm not sure we want to return here. In substrate after migration to the new model we don't need to use packer anymore. So I'd rather skip `pack_instance` for substrate contracts altogether.

File: src/lib.rs [hunk 2]
```diff
@@ -5,59 +5,76 @@
...
 pub use runtime_type::inject_runtime_type;
 
-pub struct TargetRuntime {
-	pub create_symbol: &'static str,
-	pub call_symbol: &'static str,
-	pub return_symbol: &'static str,
+pub struct TargetSymbols {
+    pub create: &'static str,
+    pub call: &'static str,
+    pub return_: &'static str,
```
Comment (NikVolf) [inline src/lib.rs]: btw don't like this `_` at the end of the identifier, especially in the public api `ret` would be

Comment (NikVolf) [reply src/lib.rs]: #114
