### PR TITLE
Preserve "deploy" when optimizing pwasm ctor module

### LINKED ISSUE #128: Cannot build simple Parity Ethereum contract
I’m using the most recent version 0.9 of `wasm-build` to build the following contract.

~~~rust
#![no_std]
use pwasm_std;

#[no_mangle]
pub fn call() {}

#[no_mangle]
pub fn deploy() {}
~~~

The build script is
~~~bash
export RUSTFLAGS="-C panic=abort -C lto=yes -C opt-level=z -C link-args=-zstack-size=65536"
cargo build --target wasm32-unknown-unknown
wasm-build --target=wasm32-unknown-unknown ./target my_contract
~~~

This results in the error 
~~~
Build error: Packing failed due to module structure error: No exported `deploy` symbol. Sure used correct libraries for building contracts?
~~~

If I add the `--skipt-optimization` flag I get
~~~
./target/my_contract.wasm:0000089: error: redefinition of export "call"
~~~

This problem was also raised in https://github.com/paritytech/pwasm-tutorial/issues/48

### PR DESCRIPTION
**Pull request by geigerzaehler**
When optimizing the constructor module for a PWasm contract the "deploy" symbol is preserved instead of the "call" symbol. Before this change `build` would error for PWasm contracts because `pack_instance` would not find the "deploy" symbol in the optimized contract.

Fixes #128

### CODE REVIEW

**Comment by geigerzaehler** [comment]
It would be prudent to add some tests for this but I’m not sure how to do it.

File: src/build.rs [hunk 1]
```diff
@@ -105,7 +105,7 @@ pub fn build(
 
 	if !skip_optimization {
 		let preserved_exports = match target_runtime {
-			TargetRuntime::PWasm(_) => vec![target_runtime.symbols().call],
```
Comment (NikVolf) [inline src/build.rs]: It should not work like this

With pwasm, first optimisation (this one) is optimising everything that is not called from `call` method, not `deploy`

The second optimisation, which is done in `pack_instance` optimises everything that is not called from `deploy` method

Comment (NikVolf) [reply src/build.rs]: hmm ok, this is actually not true ^^^, this is second optimisation actually

in #ec206fca6428d64b724a8668b431977f833e3fef there was a bug introduced
